openapi: 3.0.0
paths:
  /concerts:
    get:
      tags:
        - Concerts
      summary: Get all concerts
      responses:
        '200':
          description: List of concerts
  /concerts/import:
    post:
      tags:
        - Concerts
      summary: Import concerts from Ticketmaster API
      parameters:
        - name: city
          in: query
          schema:
            type: string
            example: London
        - name: size
          in: query
          schema:
            type: number
            example: 20
      responses:
        '200':
          description: Concerts imported successfully

  /concerts/city/{city}:
    get:
      tags:
        - Concerts
      summary: Get concerts by city
      parameters:
        - name: city
          in: path
          required: true
          schema:
            type: string
            example: London
      responses:
        '200':
          description: List of concerts in the specified city
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Concert'

  /concerts/{id}:
    get:
      tags:
        - Concerts
      summary: Get concert by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Concert found
components:
  schemas:
    Concert:
      type: object
      required:
        - name
        - artist
        - date
        - location
        - city
        - country
        - geoCoordinates
      properties:
        name:
          type: string
        artist:
          type: string
        date:
          type: string
          format: date-time
        location:
          type: string
        venue:
          type: string
        city:
          type: string
        country:
          type: string
        geoCoordinates:
          type: object
          properties:
            lat:
              type: number
            lng:
              type: number
