openapi: 3.0.0
info:
  title: Travel Proof API
  version: 1.0.0
  description: Upload and verify travel proofs for green travel rewards using Hugging Face AI models

paths:
  /travel-proofs/upload:
    post:
      tags:
        - Travel Proofs
      summary: Upload travel proof with image for Hugging Face AI verification
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - userId
                - concertId
                - travelMode
                - originLat
                - originLng
                - proofDescription
                - proofImage
              properties:
                userId:
                  type: string
                  example: 64e6ab22b6ab123456789abc
                concertId:
                  type: string
                  example: 64e6aaf9c1ab123456789abc
                travelMode:
                  type: string
                  enum: [car, train, flight, bus, walk, bike]
                originLat:
                  type: number
                  example: 51.5074
                originLng:
                  type: number
                  example: -0.1278
                proofDescription:
                  type: string
                  example: "Took the train from London Bridge to the concert venue"
                proofImage:
                  type: string
                  format: binary
      responses:
        '201':
          description: Travel proof uploaded and Hugging Face AI analysis completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TravelProofResponse'
        '400':
          description: Invalid input or missing image
        '404':
          description: Concert not found

  /travel-proofs/user/{userId}:
    get:
      tags:
        - Travel Proofs
      summary: Get user's travel proofs
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
        - name: status
          in: query
          schema:
            type: string
            enum: [pending, auto_approved, rejected]
      responses:
        '200':
          description: List of user's travel proofs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TravelProof'

  /travel-proofs/ai-stats:
    get:
      tags:
        - Travel Proofs
      summary: Get AI analysis statistics
      responses:
        '200':
          description: AI analysis performance statistics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AIAnalysisStats'

components:
  schemas:
    TravelProof:
      type: object
      properties:
        _id:
          type: string
        userId:
          type: string
        concertId:
          type: object
          properties:
            name:
              type: string
            date:
              type: string
              format: date-time
            location:
              type: string
            artist:
              type: object
              properties:
                name:
                  type: string
        travelMode:
          type: string
        originLat:
          type: number
        originLng:
          type: number
        distanceKm:
          type: number
        emissionsKgCO2:
          type: number
        proofImage:
          type: string
        proofDescription:
          type: string
        verificationStatus:
          type: string
          enum: [pending, auto_approved, rejected]
        pointsEarned:
          type: number
        isGreenTravel:
          type: boolean
        aiAnalysis:
          type: object
          properties:
            detectedTravelMode:
              type: string
            modeConfidence:
              type: number
            isGreenTravel:
              type: boolean
            greenConfidence:
              type: number
            overallConfidence:
              type: number
            reason:
              type: string
            autoApproved:
              type: boolean
            autoApprovalReason:
              type: string
            analyzedAt:
              type: string
              format: date-time

    AIAnalysisStats:
      type: object
      properties:
        totalAnalyzed:
          type: number
        autoApproved:
          type: number
        averageConfidence:
          type: number
        accuracyRate:
          type: number
        autoApprovalRate:
          type: number

    TravelProofResponse:
      type: object
      properties:
        message:
          type: string
        travelProof:
          type: object
          properties:
            id:
              type: string
            travelMode:
              type: string
            distanceKm:
              type: number
            emissionsKgCO2:
              type: number
            isGreenTravel:
              type: boolean
            pointsEarned:
              type: number
            verificationStatus:
              type: string
            aiAnalysis:
              type: object
              properties:
                detectedTravelMode:
                  type: string
                modeConfidence:
                  type: number
                overallConfidence:
                  type: number
                autoApproved:
                  type: boolean
                reason:
                  type: string
                autoApprovalReason:
                  type: string 