openapi: 3.0.0
paths:
  /users:
    get:
      tags:
        - Users
      summary: Get all users
      responses:
        '200':
          description: List of users
    post:
      tags:
        - Users
      summary: Create a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created
  /users/{id}:
    get:
      tags:
        - Users
      summary: Get user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A user

  /users/{id}/profile:
    get:
      tags:
        - Users
      summary: Get complete user profile with travel history
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Complete user profile with travel logs and emissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '404':
          description: User not found
components:
  schemas:
    User:
      type: object
      required:
        - name
        - email
      properties:
        name:
          type: string
        email:
          type: string
        preferredTransportMode:
          type: string
        rewardPoints:
          type: number
        badges:
          type: array

    UserProfile:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        email:
          type: string
        preferredTransportMode:
          type: string
        rewardPoints:
          type: number
        badges:
          type: array
          items:
            type: string
        totalEmissionsKgCO2:
          type: number
        travelLogs:
          type: array
          items:
            $ref: '#/components/schemas/TravelLog'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
